[package]
name = "server-ws"
version = "0.1.0"
edition = "2024"

[dependencies]
tungstenite = "0.28.0"
serde={version = "1.0.228", features = ["derive"]}
serde_json="1.0.145"
bytes="1.11.0"
dashmap = "5"
chrono = "0.4"